apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
        name: samarth-eks-cluster
        region: ap-south-1
nodeGroups:
        - name: ng1
          desiredCapacity: 3
          instanceType: t2.micro
          ssh:
                 publicKeyName: newaaccount


        - name: ng-1
          minSize: 3
          maxSize: 5
          instancesDistribution:
             maxPrice: 0.017
             instanceTypes: ["t3.small", "t3.medium"] #we have to list atleast one instance type
             onDemandBaseCapacity: 0
             onDemandPercentageAboveBaseCapacity: 50
             spotInstancePools: 2
          ssh:
                  publicKeyName: newaaccount